version: '3.2'

services:

  abc-postgres:
    container_name: abc-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/pgdata
    volumes:
      - abc-postgres:/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - abc  

  abc-interface:
    build: 
      context: ./interface/
      dockerfile: Dockerfile 
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}     
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}      
    restart: unless-stopped 
    depends_on: 
      - abc-postgres 
    networks:
      - abc  

networks:
  abc:
    driver: bridge
  
volumes:
  abc-postgres:
  