version: '3.2'

services:
  abc-interface:
    container_name: "abc-interface-dev"
    entrypoint: [ "python", "manage.py", "runserver", "0.0.0.0:1234" ]
    volumes:
      - ./interface:/interface
    ports:
      - "1234:1234"