- name: Test code 
  shell: |
    cd ./interface
    pytest
  register: result
  failed_when: >
    "FAILURES" in result.stdout or "FAILURES" in result.stderr

- name: Pull Pet Project
  shell: |           
      cd /var/www/education
      git pull origin master
      docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
      
- name: Prune docker 
  shell: |
    docker system prune -f
    docker container prune -f
    docker image prune -f --all
    docker network prune -f

- name: Dump
  shell: |       
    cd /var/www/education  
    docker exec -it abc-postgres pg_dump -cU abc_user abc_service > db.sql
  ignore_errors: true

- name: Copy DB
  shell: |     
    cd /var/www/education   
    rm -rf /root/ABC-Service/db.sql
    cp -f db.sql /root/ABC-Service/db.sql
  ignore_errors: true

- name: Restore DB
  shell: |       
    cd /root/ABC-Service 
    cat db.sql | docker exec -i abc-postgres psql -U abc_user -d abc_service
  ignore_errors: true