# Generated by Django 4.1.3 on 2023-03-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='complexity',
            field=models.CharField(default='Complexity', max_length=50),
        ),
        migrations.AddField(
            model_name='snippet',
            name='example',
            field=models.TextField(default='Example'),
        ),
    ]
