# Generated by Django 4.1.3 on 2023-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_snippet_complexity_snippet_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='complexity',
            field=models.CharField(default='', max_length=50, verbose_name='Complexity'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='example',
            field=models.TextField(default='', max_length=10000, verbose_name='Example'),
        ),
    ]
