# Generated by Django 4.1.3 on 2023-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_snippet_complexity_alter_snippet_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='complexity',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
    ]
